// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frctnpnikgswmkrvpdtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyY3RucG5pa2dzd21rcnZwZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxMDgwNjQsImV4cCI6MjA0NzY4NDA2NH0.Mfk_F_3H7sqN97EyJYsy_Uow7TjBhThpJ9inw5R1ZNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);